/**
 * Playlist display component with Spotify-style design
 */

'use client';

import { SpotifyTrack } from '@/lib/spotify-api';
import TrackCard from './TrackCard';
import { shuffleArray } from '@/lib/spotify-utils';
import { useState } from 'react';

interface PlaylistDisplayProps {
  tracks: SpotifyTrack[];
  emotion?: string;
  title?: string;
  onPlayTrack?: (track: SpotifyTrack) => void;
}

export default function PlaylistDisplay({
  tracks,
  emotion,
  title = 'Your Emotion-Based Playlist',
  onPlayTrack,
}: PlaylistDisplayProps) {
  const [shuffledTracks, setShuffledTracks] = useState<SpotifyTrack[]>(tracks);
  const [isShuffled, setIsShuffled] = useState(false);
  const [copySuccess, setCopySuccess] = useState(false);

  const handleShuffle = () => {
    if (isShuffled) {
      setShuffledTracks(tracks);
      setIsShuffled(false);
    } else {
      setShuffledTracks(shuffleArray(tracks));
      setIsShuffled(true);
    }
  };

  const handleCopyTrackList = () => {
    const trackList = tracks
      .map((track, i) => `${i + 1}. ${track.name} - ${track.artist}`)
      .join('\n');
    navigator.clipboard.writeText(trackList);
    setCopySuccess(true);
    setTimeout(() => setCopySuccess(false), 2000);
  };

  const handleOpenAllInSpotify = () => {
    // Open first 5 tracks in Spotify (to avoid popup blocker issues)
    const tracksWithUrls = tracks.filter(t => t.external_url).slice(0, 5);
    tracksWithUrls.forEach((track, index) => {
      if (track.external_url) {
        setTimeout(() => {
          window.open(track.external_url, '_blank');
        }, index * 500); // Stagger the openings
      }
    });
  };

  const displayTracks = isShuffled ? shuffledTracks : tracks;
  const spotifyTracks = tracks.filter(t => t.id && t.id.startsWith('spotify:') || t.external_url);

  return (
    <div className="w-full">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-white">{title}</h2>
          <p className="text-sm text-zinc-400 mt-1">
            {tracks.length} tracks • Generated by EmoRec • Powered by Spotify
          </p>
        </div>

        {/* Controls */}
        <div className="flex gap-3">
          <button
            onClick={handleCopyTrackList}
            className="px-4 py-2 rounded-full bg-white/10 text-white hover:bg-white/20 transition-all font-medium"
            title="Copy track list"
          >
            {copySuccess ? '✓ Copied!' : '📋 Copy List'}
          </button>
          
          <button
            onClick={handleShuffle}
            className={`
              px-4 py-2 rounded-full font-medium transition-all
              ${
                isShuffled
                  ? 'bg-green-500 text-black hover:bg-green-400'
                  : 'bg-white/10 text-white hover:bg-white/20'
              }
            `}
          >
            🔀 {isShuffled ? 'Unshuffle' : 'Shuffle'}
          </button>
          
          {spotifyTracks.length > 0 && (
            <button
              onClick={handleOpenAllInSpotify}
              className="px-6 py-2 rounded-full bg-green-500 text-black font-medium hover:bg-green-400 transition-colors"
              title="Open tracks in Spotify"
            >
              🎵 Open in Spotify
            </button>
          )}
        </div>
      </div>

      {/* Tracks list */}
      <div className="space-y-1">
        {displayTracks.map((track, index) => (
          <TrackCard
            key={`${track.id}-${index}`}
            track={track}
            index={index}
            emotion={emotion}
            onPlay={onPlayTrack}
          />
        ))}
      </div>

      {/* Playlist Stats */}
      <div className="mt-6 pt-6 border-t border-white/10">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-center">
          <div>
            <div className="text-2xl font-bold text-white">{tracks.length}</div>
            <div className="text-sm text-zinc-400">Total Tracks</div>
          </div>
          <div>
            <div className="text-2xl font-bold text-white">{spotifyTracks.length}</div>
            <div className="text-sm text-zinc-400">From Spotify</div>
          </div>
          <div>
            <div className="text-2xl font-bold text-white">
              {Math.round(tracks.reduce((sum, t) => sum + t.similarity_score, 0) / tracks.length * 100)}%
            </div>
            <div className="text-sm text-zinc-400">Avg Match Score</div>
          </div>
          <div>
            <div className="text-2xl font-bold text-white">
              {tracks.filter(t => t.audio_features).length}
            </div>
            <div className="text-sm text-zinc-400">With Audio Features</div>
          </div>
        </div>
      </div>
    </div>
  );
}
